name: build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: apt install
      working-directory: ${{ github.workspace }}
      run: sudo apt install gnu-efi build-tools -y

    - name: configure
      working-directory: ${{ github.workspace }}
      run: ./build.sh
